### PR TITLE
Use paket instead of nuget

### PR DESCRIPTION
**Pull request by Stift**
I converted the whole repository to use paket instead of nuget. This should be safe as we want only one version to use in all projects etc.
I also introduced one global sln file as this gives us the ability to look on one sln instead of handdling with all the load time of VS per sln. Also the sln is organised respectively to the order of the repo.
To use paket, do a `git clean` before so that you can really see what happens and then do `p restore` to get all the dependencies downloaded.. Once this is done you can start coding. The `p` is a shortcut I invented, the p.sh was not tested by me. I recommend to test it once on a Mac, if you want support for that.
If you don't want to have this branch is also fine. I'll maintain it for me and will merge your stuff into it, if needed.

### CODE REVIEW

**Comment by wki** [comment]
wow! Thank you very much. I will check out your patch into a branch "usePaket" so people may choose which version to use. I will change the line breaks to unix-Linefeeds for the p.sh file.

**Comment by Stift** [comment]
I already fixed that by now. No worries.

**Comment by forki** [comment]
Cool. Next stop: conversion to a real programming language ;-) 

*I show myself out*

**Comment by Stift** [comment]
Yeah. This is the spartakiade and at least to get the ppl in the model of AKKA has some advantage. But I think @jfellien would be glad to hear about your proposal for next year. :wink:
Maybe I will transfer the code in a real language like VB.  :fearful:

**Comment by wki** [comment]
Christian, thank you very much for your assistance. pull request merged into branch "usePaket". See you on Sunday :-)

**Pull request closed without merging**
